---
- name: Configure Frontend Server
  hosts: frontend
  become: yes

  vars:
    frontend_url: https://raw.githubusercontent.com/daws-90s/expense-documentation/refs/heads/main/artifacts/expense-frontend-v3.tar.gz

  tasks:

    - name: Enable nginx module
      command: dnf module enable nginx:1.24 -y

    - name: Install nginx
      dnf:
        name: nginx
        state: present

    - name: Remove default html directory
      file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create html directory
      file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download frontend application
      get_url:
        url: "{{ frontend_url }}"
        dest: /tmp/frontend.tar.gz

    - name: Extract frontend
      unarchive:
        src: /tmp/frontend.tar.gz
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy expense nginx configuration
      template:
        src: expense.conf.j2
        dest: /etc/nginx/conf.d/expense.conf

    - name: Validate nginx configuration
      command: nginx -t
      changed_when: false

    - name: Enable and restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes