---
- name: Configure Frontend Server
  hosts: frontend
  become: yes

  vars:
    frontend_url: https://raw.githubusercontent.com/daws-90s/expense-documentation/refs/heads/main/artifacts/expense-frontend-v3.tar.gz
    web_root: /usr/share/nginx/html

  tasks:

    - name: Enable nginx module
      command: dnf module enable nginx:1.24 -y
      ignore_errors: yes

    - name: Reinstall nginx
      shell: |
        dnf reinstall -y nginx || dnf install -y nginx

    - name: Remove old web root
      file:
        path: "{{ web_root }}"
        state: absent

    - name: Create web root
      file:
        path: "{{ web_root }}"
        state: directory

    - name: Download frontend
      get_url:
        url: "{{ frontend_url }}"
        dest: /tmp/frontend.tar.gz

    - name: Extract frontend
      unarchive:
        src: /tmp/frontend.tar.gz
        dest: "{{ web_root }}"
        remote_src: yes

    - name: Copy nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Validate nginx configuration
      command: nginx -t
      changed_when: false

    - name: Enable nginx
      service:
        name: nginx
        enabled: yes
        state: restarted